webtalk_init -webtalk_dir C:\\Users\\jon.montero\\Downloads\\MaquetaFinal\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-11-15 19:31:17" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ipo6mtvik9jvkhragd8q9mm59n" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.791 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1636999508745" -context "vitis\\\\platform/1636999508745"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1636999508745"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1636999508745"
webtalk_add_data -client vitis -key processor -value "psu_cortexa53" -context "vitis\\\\platform/1636999508745"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1636999508745"
webtalk_add_data -client vitis -key uid -value "1636999576383" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key processor -value "cortex-a53" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key device_family -value "zynquplus" -context "vitis\\\\application/1636999576383"
webtalk_add_data -client vitis -key fpga -value "xczu3eg" -context "vitis\\\\application/1636999576383"
webtalk_transmit -clientid 960687041 -regid "" -xml C:\\Users\\jon.montero\\Downloads\\MaquetaFinal\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Users\\jon.montero\\Downloads\\MaquetaFinal\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Users\\jon.montero\\Downloads\\MaquetaFinal\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
